name: appointease
description: Appointment booking app for professionals and clients.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Navigation
  go_router: ^13.2.0

  # HTTP client
  dio: ^5.4.3+1

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Calendar
  table_calendar: ^3.1.1

  # Fonts
  google_fonts: ^6.2.1

  # Local notifications
  flutter_local_notifications: ^17.2.1+1
  timezone: ^0.9.4

  # JSON serialization
  json_annotation: ^4.9.0

  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
